### ISSUE TITLE
Shrink repo - from 35mb!

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/google-deployment-manager-neo4j#1]
For some reason this repo is 35mb.  Guessing someone dumped binaries in here at some point.  Should nuke those.

**Comment by drumcircle** [comment]
We just added 30mb with APOC.  Is this a problem actually?  What is unecessary?

**Comment by benofben** [comment]
Are you sure we added 30mb to the GitHub repo?  

Usually a GitHub repo wouldn't have binaries in it.  There's even a tool that exists specifically to strip them out.  https://rtyley.github.io/bfg-repo-cleaner/

I suspect somebody commited something they shouldn't have a while back.  It's an issue because git clone takes far longer than it should when repos grow from a few kb to mb.

**Comment by benofben** [comment]
Looks like this is still 15mb.  I bet someone accidentally dropped a binary in here. 

(base) jupyter@ben-fiddling:~$ git clone https://github.com/neo4j-partners/google-deployment-manager-neo4j.git
Cloning into 'google-deployment-manager-neo4j'...
remote: Enumerating objects: 6485, done.
remote: Counting objects: 100% (6485/6485), done.
remote: Compressing objects: 100% (1947/1947), done.
remote: Total 6485 (delta 4593), reused 6317 (delta 4451), pack-reused 0
Receiving objects: 100% (6485/6485), 15.02 MiB | 26.66 MiB/s, done.
Resolving deltas: 100% (4593/4593), done.
(base) jupyter@ben-fiddling:~$

**Comment by harshitsinghvi22** [comment]
@benofben  Please verify now

```
 harshit@MacBook-Pro-4  ~/repos/harshitsinghvi22                                                                                                     ✔  11206  09:32:28
 $ git clone git@github.com:neo4j-partners/google-deployment-manager-neo4j.git
Cloning into 'google-deployment-manager-neo4j'...
remote: Enumerating objects: 7191, done.
remote: Counting objects: 100% (2130/2130), done.
remote: Compressing objects: 100% (957/957), done.
remote: Total 7191 (delta 1186), reused 2087 (delta 1155), pack-reused 5061
Receiving objects: 100% (7191/7191), 1.93 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (4874/4874), done.

```

**Comment by benofben** [comment]
Great.  Thanks.
