### ISSUE TITLE
Fix License Logic

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/google-deployment-manager-neo4j#2]

**Comment by drumcircle** [comment]
On it.

**Comment by drumcircle** [comment]
Fixed in [feature/2_fix_license_logic]

(https://github.com/neo4j-partners/google-deployment-manager-neo4j/tree/feature/2_fix_license_logic) 

Please verify and close.

**Comment by drumcircle** [comment]
Fixed pending verification

**Comment by benofben** [comment]
I can't access bloom on http://ip:7474/browser/bloom/. I think that's where it's supposed to be running.  Do I have a bad key or some other issue?

**Comment by benofben** [comment]
Still no joy on Bloom.  Trying with your license file next...  
![image](https://user-images.githubusercontent.com/8282917/159944106-76116b65-7651-407d-a089-a9b3294b3a51.png)

**Comment by benofben** [comment]
Yeah, tried w your license file.  No joy there either.

**Comment by drumcircle** [comment]
> Still no joy on Bloom. Trying with your license file next... ![image](https://user-images.githubusercontent.com/8282917/159944106-76116b65-7651-407d-a089-a9b3294b3a51.png)

The URL to try is /bloom not /browser/bloom

**Comment by benofben** [comment]
It's working for me now at http://34.74.217.12:7474/bloom/

So, this is just a user (me) error.  The URL is different on Aura which is what was messing me up.  So seems like this works!  Thank you.
