### ISSUE TITLE
Output Neo4j Browser URL

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/google-deployment-manager-neo4j#7]
Notes from the GCP people ---

Here is the relevant public docs on [using references](https://cloud.google.com/deployment-manager/docs/configuration/use-references) and [exposing information using outputs](https://cloud.google.com/deployment-manager/docs/configuration/expose-information-outputs), which should help explain how these features work.

**Comment by benofben** [comment]
Same thing from the Google people again (support outsourced to Tech Mahindra now...)

2.  admin URL -  [This](https://console.cloud.google.com/marketplace/product/click-to-deploy-images/pimcore) example solution has all the different types of fields that you're looking for which we believe are helpful in this case.

**Comment by ojhughes** [comment]
This is fixed in https://github.com/neo4j-partners/google-deployment-manager-neo4j/releases/tag/5.1
