### ISSUE TITLE
Close Ports

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/google-deployment-manager-neo4j#8]
Ports that should be only open internally are open globally because of external IP dependency.

Suggestion from Google ---

If the partner only wants certain ports to be accessible between instances in the deployment, they can use sourceTags and targetTags on the firewall ([public docs](https://cloud.google.com/vpc/docs/firewalls#rule_assignment), [autogen example](https://github.com/GoogleCloudPlatform/deploymentmanager-autogen/blob/270468b0c47490d071552c048807d7096a36d08f/javatests/com/google/cloud/deploymentmanager/autogen/testdata/multivm/full_features2/golden/tier2_tier.jinja#L169-L178)).

Autogen natively supports this type of configuration - see https://github.com/GoogleCloudPlatform/marketplace-tools/blob/master/docs/autogen-reference.md#firewallrulespectrafficsource. Perhaps the partner should consider using autogen.

**Comment by benofben** [comment]
Suggestion from Google --- 

I checked the two issues we discussed last week and our team suggests the below.

Restricting traffic to deployment resources - we have two options.
* Use Autogen to generate the deployment package which has this feature built in.
* Use tags against the compute resources and use those tags here. We confirmed that tags do not consume any resources in the project. Looking at your current deployment package changes I feel this is the option to pursue.

**Comment by benofben** [comment]
I've tried to work this into the template but I'm struggling with the syntax.  I've requested a live call to work through it with Google.

**Comment by benofben** [comment]
Per Google this is not possible.  Ed and team are refactoring the template to use a load balancer and will make the change when they do that.

**Comment by ojhughes** [comment]
In the 5.1 release I configured the firewall so that internal ports such as 5000 are only available on the internal subnet
